### PR TITLE
Dev/v3.0.beta 1

### PR DESCRIPTION
**Pull request by jongund**
* Updated to use OpenA11y Evaluation Library 2.0 to support;
  * WCAG 2.1
  * ARIA 1.2
  * ARIA in HTML
  * Improved accessible name computation
  * Improved table rules
  * Updated keyboard rules
  * Fixed minor bugs
* New ruleset and rule scope filtering options
  * New First Step Rules option
* Improved element result level information
* Improved element highlighting

- [ ] User interaction and layout (Nicholas Hoyt)

* Scope filter button
* New preferences tab panel
* New ruleset and filtering options
* Labeling of summary info button

### CODE REVIEW

**Comment by nhoyt** [comment]
User interaction, styling and layout:

- [x] Scope filter button - user interactions, findability and prominence in the interface
- [x] New preferences tab panel - labeling, information architecture
- [ ] New ruleset and filtering options - labeling, information architecture
- [x] Labeling of summary info button - aria-label and title attributes

Comments: Maybe WCAG 2.2 ruleset should not appear in the options list until it can be enabled?

**Comment by jongund** [comment]
Nick,

Ok.  I can comment it out.

Jon


On Sep 25, 2023, at 4:25 PM, Nicholas Hoyt ***@***.***> wrote:



User interaction, styling and layout:

  *    Scope filter button - user interactions, findability and prominence in the interface
  *    New preferences tab panel - labeling, information architecture
  *    New ruleset and filtering options - labeling, information architecture
  *    Labeling of summary info button - aria-label and title attributes

Comments: Maybe WCAG 2.2 ruleset should not appear in the options list until it can be enabled?

**Comment by jongund** [comment]
@nhoyt 
I made the change to the WCAG 2.2 option, please review the feature again.

Jon

**Comment by jongund** [comment]
Thanks Nick, I am merging.

**Pull request merged**
