### PR TITLE
Fixed bug in CCR calculation for RGBA colors and enhanced the color info displayed for elements

### PR DESCRIPTION
**Pull request by jongund**
Uses updated evaluation library and shows the hex value of the color in the details for the CCR rule.

Evaluation library bug fix related to calculating CCR when color values are RGBA (was not utlizing Alpha channel information).

### CODE REVIEW

**Comment by nhoyt** [comment]
In CHANGELOG and README files, 'evaluation' is misspelled.

**Comment by nhoyt** [comment]
Suggestion: change variable/property name 'RGBToHEX' to rgbToHex for readability. If its usage is too widespread (i.e., used in many different files) it may not be worth changing. But suggested spelling would be more consistent with spelling of other RGB and Hex variables/properties.

**Comment by nhoyt** [comment]
Does this fix the bug that Dick Detzner found? If so, can you indicate that, and provide a link to the file he referenced for testing that shows it's been resolved.

**Comment by jongund** [comment]
I copied the ccr issue from the evaluation library to AInspector to document the issue for the next release of AInspector.  I have also added this issue to an issue that will be fixed in the pull request.

**Comment by jongund** [comment]
Nick The changes to AInspector are ready for your review.  
I tired using the rebase command, but I didn't quite understand how it worked and the commit messages are not correct.  Maybe we could go over it tomorrow.

**Review by nhoyt — APPROVED** [review]

**Pull request merged**
